/**
 * Why this exists: admins need a safe API surface to inspect failure reports
 * generated by error middleware without direct filesystem access.
 */
import { Router } from 'express';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { basename, resolve } from 'node:path';
import { ApiError } from '../../common/utils/api-error.js';
import { sendSuccess } from '../../common/utils/api-response.js';

const adminRouter = Router();
const failureLogsDir = resolve(process.cwd(), 'logs', 'failures');
const reportFilePattern = /^[A-Za-z0-9._-]+\.json$/;

const parseLimit = (rawLimit) => {
  if (rawLimit === undefined) {
    return 100;
  }

  const parsed = Number(rawLimit);
  if (!Number.isInteger(parsed) || parsed < 1 || parsed > 500) {
    throw new ApiError(400, 'INVALID_INPUT', 'limit query must be an integer from 1 to 500', {
      details: [{ field: 'limit', issue: 'Use a numeric value between 1 and 500' }],
    });
  }

  return parsed;
};

const resolveSafeReportPath = (fileName) => {
  const normalized = basename(String(fileName || '').trim());

  if (!reportFilePattern.test(normalized)) {
    throw new ApiError(400, 'INVALID_INPUT', 'Invalid report file name', {
      details: [{ field: 'fileName', issue: 'Only .json report files are allowed' }],
    });
  }

  const filePath = resolve(failureLogsDir, normalized);
  if (!filePath.startsWith(failureLogsDir)) {
    throw new ApiError(400, 'INVALID_INPUT', 'Invalid report path', {
      details: [{ field: 'fileName', issue: 'Path traversal is not allowed' }],
    });
  }

  return { normalized, filePath };
};

const parseReportFile = (filePath) => {
  const raw = readFileSync(filePath, 'utf8');
  return JSON.parse(raw);
};

adminRouter.get('/reports', (req, res, next) => {
  try {
    if (!existsSync(failureLogsDir)) {
      sendSuccess(res, req, {
        message: 'Failure reports fetched successfully',
        data: {
          count: 0,
          reports: [],
        },
      });
      return;
    }

    const limit = parseLimit(req.query.limit);
    const files = readdirSync(failureLogsDir)
      .filter((name) => reportFilePattern.test(name))
      .sort((a, b) => b.localeCompare(a))
      .slice(0, limit);

    const reports = files.map((fileName) => {
      const filePath = resolve(failureLogsDir, fileName);
      const report = parseReportFile(filePath);

      return {
        fileName,
        reportType: report.reportType || 'request-failure',
        createdAt: report.createdAt || null,
        requestId: report.requestId || null,
        taskId: report.taskId || null,
        statusCode: report.failure?.statusCode ?? null,
        errorCode: report.failure?.code || null,
        message: report.failure?.message || null,
        method: report.operation?.method || null,
        path: report.operation?.path || null,
        intentTask: report.operation?.intent?.task || null,
      };
    });

    sendSuccess(res, req, {
      message: 'Failure reports fetched successfully',
      data: {
        count: reports.length,
        reports,
      },
    });
  } catch (error) {
    next(error);
  }
});

adminRouter.get('/reports/:fileName', (req, res, next) => {
  try {
    const { normalized, filePath } = resolveSafeReportPath(req.params.fileName);

    if (!existsSync(filePath)) {
      throw new ApiError(404, 'REPORT_NOT_FOUND', `Report file "${normalized}" was not found`, {
        details: [{ field: 'fileName', issue: 'No report exists with this file name' }],
      });
    }

    const report = parseReportFile(filePath);

    sendSuccess(res, req, {
      message: 'Failure report fetched successfully',
      data: {
        fileName: normalized,
        report,
      },
    });
  } catch (error) {
    next(error);
  }
});

export { adminRouter };
